import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part 1: Foundations of Physical AI',
      items: [
        'part1/chapter1',
        'part1/chapter2',
        'part1/chapter3',
        'part1/chapter4',
      ],
    },
    {
      type: 'category',
      label: 'Part 2: Core AI Techniques for Physical Interaction',
      items: [
        'part2/chapter5',
        'part2/chapter6',
        'part2/chapter7',
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Fundamentals of Robotics',
      items: [
        'part3/chapter8',
        'part3/chapter9',
        'part3/chapter10',
        'part3/chapter11',
      ],
    },
    {
      type: 'category',
      label: 'Part 4: Advanced Topics',
      items: [
        'part4/chapter12',
        'part4/chapter13',
        'part4/chapter14',
      ],
    },
  ],
};

export default sidebars;
